# Generated by Django 4.1.6 on 2023-09-02 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(choices=[('Sub1', 'Subject1'), ('Sub2', 'Subject2'), ('Sub3', 'Subject3'), ('Sub4', 'Subject4'), ('Sub5', 'Subject5'), ('Sub6', 'Subject6')], max_length=20)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.personinfocreate')),
            ],
        ),
    ]
