# Generated by Django 4.1.6 on 2023-09-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfocreate',
            name='userid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
